//
//  main.cpp
//  Leetcode_C++
//
//  Created by chenwei on 2020/3/23.
//  Copyright © 2020 chenwei. All rights reserved.
//

#include <iostream>
#include "Leetcode_C.h"

#include "Solution2.hpp"
#include "Solution3.hpp"
#include "Solution5.hpp"
#include "Solution8.hpp"
#include "Solution9.hpp"
#include "Solution15.hpp"
#include "Solution17.hpp"
#include "Solution18.hpp"
#include "Solution21.hpp"
#include "Solution24.hpp"
#include "Solution25.hpp"
#include "Solution28.hpp"
#include "Solution46.hpp"
#include "Solution47.hpp"
#include "Solution51.hpp"
#include "Solution54.hpp"
#include "Solution61.hpp"
#include "Solution62.hpp"
#include "Solution67.hpp"
#include "Solution70.hpp"
#include "Solution72.hpp"
#include "Solution76.hpp"
#include "Solution78.hpp"
#include "Solution102.hpp"
#include "Solution106.hpp"
#include "Solution111.hpp"
#include "Solution112.hpp"
#include "Solution117.hpp"
#include "Solution120.hpp"
#include "Solution121.hpp"
#include "Solution122.hpp"
#include "Solution123.hpp"
#include "Solution131.hpp"
#include "Solution141.hpp"
#include "Solution142.hpp"
#include "Solution145.hpp"
#include "Solution148.hpp"
#include "Solution151.hpp"
#include "Solution152.hpp"
#include "Solution164.hpp"
#include "Solution188.hpp"
#include "Solution198.hpp"
#include "Solution200.hpp"
#include "Solution203.hpp"
#include "Solution208.hpp"
#include "Solution210.hpp"
#include "Solution215.hpp"
#include "Solution234.hpp"
#include "Solution236.hpp"
#include "Solution239.hpp"
#include "Solution289.hpp"
#include "Solution309.hpp"
#include "Solution322.hpp"
#include "Solution328.hpp"
#include "Solution337.hpp"
#include "Solution355.hpp"
#include "Solution445.hpp"
#include "Solution460.hpp"
#include "Solution494.hpp"
#include "Solution516.hpp"
#include "Solution542.hpp"
#include "Solution674.hpp"
#include "Solution714.hpp"
#include "Solution752.hpp"
#include "Solution820.hpp"
#include "Solution866.hpp"
#include "Solution867.hpp"
#include "Solution889.hpp"
#include "Solution912.hpp"
#include "Solution1143.hpp"
#include "Solution1162.hpp"
#include "Solution_12.hpp"
#include "Solution_61.hpp"
#include "Solution_1603.hpp"
#include "Solution_0811.hpp"
#include "Solution_0808.hpp"
#include "MyQueue.hpp"

int main(int argc, const char * argv[]) {
    Solution889().test();
    return 0;
}

